version: "3.13"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    command: >
      bash -c "
      python startup.py &&
      python pipeline.py &
      uvicorn api:app --host 0.0.0.0 --port 8000 --reload
      "
    ports:
      - "8000:8000"
    volumes:
      - .:/app
