FROM python:3.13 AS builder


RUN apt-get update && apt-get install -y \
    openjdk-11-jre-headless \
    curl \
    && apt-get clean

ENV JAVA_HOME="/usr/lib/jvm/java-11-openjdk-amd64"
ENV PATH="$JAVA_HOME/bin:$PATH"

RUN java -version

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --pre torch --index-url https://download.pytorch.org/whl/nightly/cpu

COPY . .

CMD ["python", "pipeline.py"]
