version: '3.13'

services:
  data-pipeline:
    build: .
    volumes:
      - ./data:/app/data
      - ./vectordb_workspace:/app/vectordb_workspace
    command: python pipeline.py
    restart: always

  data-initialization:
    build: .
    volumes:
      - ./data:/app/data
      - ./vectordb_workspace:/app/vectordb_workspace
    command: python startup.py
    restart: on-failure

  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./vectordb_workspace:/app/vectordb_workspace
    command: uvicorn api:app --host 0.0.0.0 --port 8000
    restart: always

networks:
  default:
    driver: bridge