FROM python:3.13 AS builder

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --pre torch --index-url https://download.pytorch.org/whl/nightly/cpu

COPY . .

CMD ["python", "pipeline.py"]
