FROM python:3.12-bullseye


RUN apt-get update && apt-get install -y \
    openjdk-17-jdk-headless \
    curl \
    && apt-get clean

ENV JAVA_HOME="/usr/lib/jvm/java-17-openjdk-arm64"
ENV PATH="$JAVA_HOME/bin:$PATH"


RUN java -version

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY startup.py .
COPY streamlit_data/ streamlit_data/

ENV PATH="/venv/bin:$PATH"

CMD ["bash", "-c", "python startup.py"]
